<?php
return [
    "decimal_point"         => ".",
    "thousand_seperator"    => ",",
    "h_home"      => "Dom",
    "h_videos"    => "Filmy Wideo",
    "h_channels"  => "Kanały",
    "h_community" => "Społeczność",
    "h_search"    => "Szukaj",
    "h_signup"    => "Utwórz Konto",
    "h_signin"    => "Zaloguj",
    "h_or"        => "lub",
    "h_subs"      => "Subskrybenci",
    "h_history"   => "Historia",
    "h_upload"    => "Przekazać Plik",
    "w_watched"   => "Oglądane Filmy Wideo",
    "w_recommend" => "Zalecane Filmy Wideo",
    "w_subscrib"  => "Subskrypcje",
    "w_featured"  => "Promowane Filmy Wideo",
    "w_popular"   => "Najpopularniejsze Filmy Wideo",
    "s_customize" => "Chcesz dostosować tę stronę główną?",
    "s_si_su"     => "<a href='/signin'>Zaloguj Się</a> lub <a href='/signup'>Zapisz Się</a> teraz!",
    "contest"     => "Konkurs Wideo",
    "contest_prm" => "Nakręć wideo, prześlij go, udostępnij!",
    "contest_th"  => "Aktualny Motyw:",
    "contest_ent" => "<a href='/upload?e=c'>Wejdź Teraz</a> | <a href='/contest'>Zobacz Wwpisy</a>",
    "view"        => "widok",
    "views"       => "widoki",
    "whatsnew"    => "Co Nowego",
    "delvid"      => "Usunięte Wideo",
    "prvvid"      => "Prywatne Wideo",
    "prtn"        => "Partnered",
    "vrfd"        => "Zweryfikowany"
];
